server:
  port: 8082

spring:
  datasource:
        url: jdbc:postgresql://sblab03.nsu.ru:5432/matsko_library_fund
        username: amatsko20205
        password:
  jpa:
    hibernate:
      naming:
        physical-strategy: ru.nsu.ccfit.databases.matsko.library_fund.config.MyPhysicalNamingStrategy
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

